export const DATA = [
  {
    id: 1,
    link: "/campus-life/campus-events/",
    image: "/n/wp-content/uploads/2020/06/ncc-1.jpg",
  },
  {
    id: 2,
    link: "/campus-life/yugadya-swachh-bharat-ncc-nss/national-service-scheme/",
    image: "/url",
  },
];

export const NATIONAL_SERVICE_SCHEMA = [
  {
    id: 1,
    tab_title: "About US",
    link: "/campus-life/campus-events/",
    image: "/n/wp-content/uploads/2020/06/ncc-1.jpg",
    sections: [
      {
        id: 1,
        title: "Vision",
        desc: "To build the youth with the mind and spirit to serve the society and work for the social uplift of the down-trodden masses of our nation as a movement.",
      },
      {
        id: 2,
        title: "Mission",
        desc: "The National Service Scheme has been functioning with the motto **NOT ME BUT YOU** in view of making the youth inspired in service of the people and hence NSS Aims Education through Community Service and Community Service through Education.",
        desc_1:
          "National Service Scheme of Karpagam Academy of Higher Education is functioning with Five Self Financing Units recognized by the Ministry of Youth Affairs & Sports, Government of India.",
        table: [
          {
            id: 1,
            name: "Dr. A. Dharmaraj",
            department: "Department of Management",
            designation: "Director, Extension Programmes",
          },
          {
            id: 2,
            name: "Mr. K. Veerasamy",
            department: "Department of Computer Science",
            designation: "NSS Programme Officer – Unit I",
          },
          {
            id: 3,
            name: "Dr. M. Deivanayaki",
            department: "Department of Science and Humanities",
            designation: "NSS Programme Officer – Unit II",
          },
          {
            id: 4,
            name: "Mr. M. Kannan",
            department: "Department of Pharmacy",
            designation: "NSS Programme Officer – Unit III",
          },
          {
            id: 5,
            name: "Mrs. K. K. Saritha Mol",
            department: "Department of Commerce",
            designation: "NSS Programme Officer – Unit IV",
          },
          {
            id: 6,
            name: "Dr. M. Kalaimathi",
            department: "Department of Chemistry",
            designation: "NSS Programme Officer – Unit V",
          },
        ],
        desc3:
          "We have brought a lot of awareness through N.S.S. It brings to all of us a platform to serve society and brings happiness and smile on many faces. We created a hub to deliver service to society by showcasing our Knowledge. So, it's not simply an association; a reason to achieve our objective and carry on the legacy for the coming years. NSS undertake various activities either independently or along with Government departments and NGOs.The following are the highlights of various activities.",
        activities: [
          "An awareness programme for water conservation, energy conservation, usage of renewable energy such as solar energy and Government subsidy available (to use solar energy at home, offices and institutions) are conducted.",
          "The students cleaned the Government High Schools in adopted villages, white washed the class rooms, planted trees and totally changed the ambience of the schools.",
          "NSS organized intramural sports competitions at Government Schools.",
          "Students educated the rural people on the advantages of digital payments by providing them hands on experience.",
          "A good number of wards/spouses of many rural households are overseas and to enable them to communicate with their wards, the households were given training on computer functional literacy such as sending and receiving an email, communicating through skypes and in digital transactions.",
          "Various medical camps such as general medical camps, eye camps were organized along with government, private medical agencies. The camps also created awareness about prevention and protection from many communicable and non-communicable diseases.",
          "Campaigns were conducted in Rural on Sanitation and Hygiene.",
          "Education-related programmes.",
          "Celebration of National and International Days.",
        ],
        desc4:
          "Also, many social awareness programmes such as Tobacco-Free Village, Avoiding Open Defecation, Solid Waste Management, Plastic Eradication, Tree Plantation, Rural Women’s Day, International Women’s Day, Indian Constitution Day, Poshan Abhiyan, Jal Sakthi Abhiyan and Organic Farming etc., were organized in the villages. Awareness Programmes conducted on Environmental Pollution and Its Control Measures, Child Obesity Prevention, Breast Cancer, Organ Donation, Child abuse and Legal Literacy.",
        desc5:
          "Students voluntarily donated blood to the needy people in the government and private hospitals whenever they need. Volunteers also render their helping hand spontaneously at the time of emergency created by natural calamities such as Kaja Cyclone by free supply of material and food items.",
      },
    ],
  },
  {
    id: 2,
    tab_title: "Regular Activities",
    title: "Annual Special Camp ",
    desc: "NSS Units of KAHE organize Seven Days Annual Special Camps regularly at adopted villages.",
    activities: {
      id: 1,
      title: "Regular Activities",
      list: [
        "Anti-Ragging Awareness Programme (At KAHE)",
        "Swachh Bharat Awareness",
        "Swachhata Pakhwada Campaigns",
        "Swachh Bharat Mission",
        "Swachh Survekshan",
        "Poshan Abhiyan BETI Bachao Beti Padhao",
        "Unnat Bharat Abhiyan Awareness programme",
        "Village Development Programme",
        "Rural Development programme",
        "Tree Plantation (KAHE & adopted Villages)",
        "Health and Hygiene Programme",
        "Renovation Lakes and Ponds at adopted villages",
        "Free Medical & Rural Assistance Camps (Adopted Villages & Tribal Villages)",
        "Legal Literacy Programme (At KAHE)",
        "Higher Education Awareness among School Students",
        "Village Cleaning Programmes (Adopted Villages)",
        "Campus Cleaning Programmes (At KAHE)",
        "Environmental Awareness Programme (Adopted Villages)",
        "General Medical Camps (Adopted Villages)",
        "Trekking Adventure Camps",
        "Blood Donation Camp (At KAHE)",
        "Conservation Birds and Wild Animals",
        "Temple Campus Cleaning at adopted villages",
        "World Breast Feeding Week",
        "World Breast Cancer day",
        "AIDS Day",
        "Road Safety Week",
        "Energy Conservation day",
        "Women's Day",
        "Child obesity",
        "Plastic Free Village",
        "Helmet and Importance of Trees",
        "Child Abuse at Schools",
        "Dengue Awareness",
        "Celebrations of national and international days",
      ],
    },
  },
  {
    id: 3,
    tab_title: "Events",
    section: [
      {
        events_table: {
          headings: [
            "S. No.",
            "Name of the activity",
            "Date",
            "Organizing unit/ agency/ collaborating agency",
            "Name of the scheme",
            "Year of the activity",
          ],
          data: [
            {
              s_no: 1,
              activity_name:
                "Central Govt. Welfare Schemes Awareness camp at Nagamam, Pollachi",
              date: "19.01.2021",
              organizing_unit:
                "NSS With Field Outreach Bureau, Ministry of Information & Broadcasting, Government of India",
              scheme_name:
                "Swachhata Pakhwada, COVID 19 Vaccine Administration Awareness, Medical Camp & Voters Awareness",
              year_of_activity: "19.01.2021",
            },
            {
              s_no: 2,
              activity_name:
                "Central Govt. Welfare Schemes Awareness camp at Nagarthur Sangam, Pollachi",
              date: "18.01.2021",
              organizing_unit:
                "NSS With Field Outreach Bureau, Ministry of Information & Broadcasting, Government of India",
              scheme_name:
                "Swachhata Pakhwada, COVID 19 Vaccine Administration Awareness, Medical Camp & Voters Awareness",
              year_of_activity: "18.01.2021",
            },
            {
              s_no: 3,
              activity_name:
                "Webinar to observe international Day of Epidemic Preparedness",
              date: "28.12.2020",
              organizing_unit:
                "NSS With Field Outreach Bureau, Ministry of Information & Broadcasting, Government of India",
              scheme_name: "Epidemic Awareness",
              year_of_activity: "2020-2021",
            },
            {
              s_no: 4,
              activity_name: "World Computer Literacy Day Webinar",
              date: "02.12.2020",
              organizing_unit: "NSS",
              scheme_name: "Awareness Webinar",
              year_of_activity: "2020-2021",
            },
            {
              s_no: 5,
              activity_name: "World AIDS Day",
              date: "01.12.2020",
              organizing_unit: "NSS",
              scheme_name: "Awareness Programme",
              year_of_activity: "2020-2021",
            },
            {
              s_no: 6,
              activity_name:
                "Webinar on Constitution Values and Fundamental Principles of Indian Constitution",
              date: "27.11.2020",
              organizing_unit: "NSS",
              scheme_name: "Celebration of Constitution Day",
              year_of_activity: "2020-2021",
            },
            {
              s_no: 7,
              activity_name:
                "Universal Children Day & Child Rights during Pandemic",
              date: "20.11.2020",
              organizing_unit:
                "NSS With Field Outreach Bureau, Ministry of Information & Broadcasting, Government of India",
              scheme_name: "Celebration of Universal Children Day",
              year_of_activity: "2020-2021",
            },
            {
              s_no: 8,
              activity_name: "COVID-19 Awareness Poster Release Programme",
              date: "18.11.2020",
              organizing_unit:
                "NSS With Field Outreach Bureau, Ministry of Information & Broadcasting, Government of India",
              scheme_name: "COVID 19",
              year_of_activity: "2020-2021",
            },
            {
              s_no: 9,
              activity_name: "Jan Andolan Campaign on COVID 19",
              date: "17.11.2020",
              organizing_unit:
                "NSS With Field Outreach Bureau, Ministry of Information & Broadcasting, Government of India",
              scheme_name: "COVID 19",
              year_of_activity: "2020-2021",
            },
            {
              s_no: 10,
              activity_name:
                "UNNAT BHARAT ABHYAN Awareness Programme on COVID-19",
              date: "17.11.2020",
              organizing_unit:
                "NSS With Field Outreach Bureau, Ministry of Information & Broadcasting, Government of India",
              scheme_name: "COVID 19",
              year_of_activity: "2020-2021",
            },
            {
              s_no: 11,
              activity_name:
                "Peace building Competencies for next Generation Purple Leaders",
              date: "16.11.2020",
              organizing_unit: "NSS",
              scheme_name: "Tolerance Day",
              year_of_activity: "2020-2021",
            },
            {
              s_no: 12,
              activity_name:
                "International Day of Tolerance awareness webinar on Mahatma Gandhi's Practice of tolerance",
              date: "16.11.2020",
              organizing_unit: "NSS",
              scheme_name: "Tolerance Day",
              year_of_activity: "2020-2021",
            },
            {
              s_no: 13,
              activity_name: "World Diabetes Day 2020",
              date: "12.11.2020",
              organizing_unit: "NSS with Faculty of Pharmacy",
              scheme_name: "World Diabetes Day",
              year_of_activity: "2020-2021",
            },
            {
              s_no: 14,
              activity_name: "Webinar on Gandhiyan Thoughts",
              date: "02.10.2020",
              organizing_unit:
                "NSS With Field Outreach Bureau, Ministry of Information & Broadcasting, Government of India",
              scheme_name: "Endowment Lecture",
              year_of_activity: "2020-2021",
            },
            {
              s_no: 15,
              activity_name:
                "Role of Media & Social Media during COVID 19-Pandemic",
              date: "21.08.2020",
              organizing_unit:
                "Field Outreach Bureau, Ministry of Information & Broadcasting, Government of India",
              scheme_name: "COVID 19",
              year_of_activity: "2020-2021",
            },
            {
              s_no: 16,
              activity_name: "Webinar on National Education Policy",
              date: "13.08.2020",
              organizing_unit:
                "NSS With Field Outreach Bureau, Ministry of Information & Broadcasting, Government of India",
              scheme_name: "Awareness",
              year_of_activity: "2020-2021",
            },
            {
              s_no: 17,
              activity_name: "Safe Hand Wash Training Protection from COVID-19",
              date: "05.07.2020",
              organizing_unit: "NSS",
              scheme_name: "COVID 19",
              year_of_activity: "2020-2021",
            },
            {
              s_no: 18,
              activity_name: "Safe Hand Wash Training Protection from COVID-19",
              date: "04.04.2020",
              organizing_unit: "NSS",
              scheme_name: "COVID 19",
              year_of_activity: "2020-2021",
            },
            {
              s_no: 19,
              activity_name: "COVID-19 -Volunteering Service",
              date: "22.03.2020 to 30.09.2020",
              organizing_unit: "NSS student with Police Department Salem",
              scheme_name: "COVID-19 Volunteering service",
              year_of_activity: "2019-2020",
            },
            {
              s_no: 20,
              activity_name: "Tree Plantation-Nagamanackenpalsyam",
              date: "14.03.2020",
              organizing_unit: "NSS",
              scheme_name: "Environment Conservation",
              year_of_activity: "2019-2020",
            },
            {
              s_no: 21,
              activity_name: "Ek Bharat Shreshtha Bharat",
              date: "13.03.2020",
              organizing_unit:
                "NSS with Field Outreach Bureau, Ministry of Information & Broadcasting, Government of India",
              scheme_name: "Awareness Programme",
              year_of_activity: "2019-2020",
            },
            {
              s_no: 22,
              activity_name:
                "Traditional Handicraft Items Making Training for Women",
              date: "10.03.2020",
              organizing_unit:
                "NSS with Field Outreach Bureau, Ministry of Information & Broadcasting, Government of India",
              scheme_name: "Micro Entrepreneurship Development Programme",
              year_of_activity: "2019-2020",
            },
            {
              s_no: 23,
              activity_name: "Women's Day Celebration at Karpagam Hospital",
              date: "09.03.2020",
              organizing_unit: "NSS with Karpagam Hospital",
              scheme_name: "Women's Day Celebration",
              year_of_activity: "2019-2020",
            },
            {
              s_no: 24,
              activity_name: "Womens bay Awareness Programme-Chetitpaliyam",
              date: "09.03.2020",
              organizing_unit: "NSS with Karpsgarn Hospital",
              scheme_name: "Womens bay Celebration",
              year_of_activity: "2019-2020",
            },
            {
              s_no: 25,
              activity_name: "Womens Bay Celebration Bikathon Rally",
              date: "09.03.2020",
              organizing_unit:
                "NSS with Field Outreach Bureau, Ministry of Information & Broadcasting, Government of India and Karpsgarn Hospital",
              scheme_name: "Womens Bay Celebration",
              year_of_activity: "2019-2020",
            },
            {
              s_no: 26,
              activity_name:
                "Womens Bay Celebration Film Show on Inspiring women",
              date: "08.03.2020",
              organizing_unit:
                "NSS with Field Outreach Bureau, Ministry of Information & Broadcasting, Government of India",
              scheme_name: "Womens Bay Celebration",
              year_of_activity: "2019-2020",
            },
            {
              s_no: 27,
              activity_name: "Awareness Campaign on women's rights",
              date: "08.03.2020",
              organizing_unit:
                "NSS with Field Outreach Bureau, Ministry of Information & Broadcasting, Government of India",
              scheme_name: "Womens Bay Celebration",
              year_of_activity: "2019-2020",
            },
            {
              s_no: 28,
              activity_name: "Agrothon 2020 Kids Marathon",
              date: "08.03.2020",
              organizing_unit: "NSS with DHF Foundation",
              scheme_name: "Development of Agriculture",
              year_of_activity: "2019-2020",
            },
            {
              s_no: 29,
              activity_name: "Womens Bay Celebration Rally",
              date: "08.03.2020",
              organizing_unit:
                "NSS with Field Outreach Bureau, Ministry of Information & Broadcasting, Government of India",
              scheme_name: "Womens Bay Celebration",
              year_of_activity: "2019-2020",
            },
            {
              s_no: 30,
              activity_name:
                "Womens Bay Celebration-Medical Camp, Corona Virus Awareness, Awareness on Poshan Abhiyan and Swachh Bharat",
              date: "07.03.2020",
              organizing_unit:
                "NSS with Field Outreach Bureau, Ministry of Information & Broadcasting, Government of India and Karpsgarn Hospital",
              scheme_name: "Awareness on Corona Virus",
              year_of_activity: "2019-2020",
            },
            {
              s_no: 31,
              activity_name: "Womens Bay Awareness Seminar and Events",
              date: "06.03.2020",
              organizing_unit: "NSS",
              scheme_name: "Women's Day Celebration",
              year_of_activity: "2019-2020",
            },
            {
              s_no: 32,
              activity_name: "Awareness on Organic Agriculture Products",
              date: "04.03.2020",
              organizing_unit: "NSS With Pasumal Desarn",
              scheme_name: "Awareness on Organic Foods",
              year_of_activity: "2019-2020",
            },
            {
              s_no: 33,
              activity_name:
                "Mahila Adhikar Abhiyan Special Awareness Programme-Power Walkathon Rally",
              date: "03.03.2020",
              organizing_unit:
                "NSS with Field Outreach Bureau, Ministry of Information & Broadcasting, Government of India",
              scheme_name: "Women's Day Celebration",
              year_of_activity: "2019-2020",
            },
            {
              s_no: 34,
              activity_name: "Green Initiative Activities",
              date: "Feb-March 2020",
              organizing_unit: "NSS",
              scheme_name: "Green Initiative Activities of NSS",
              year_of_activity: "2019-2020",
            },
            {
              s_no: 35,
              activity_name: "Blood Donation Camp",
              date: "20.02.2020",
              organizing_unit: "YRC with Indian Medical Association Coimbatore",
              scheme_name: "Save Life",
              year_of_activity: "2019-2020",
            },
            {
              s_no: 36,
              activity_name:
                "Intramural Sports Day for Government Higher Secondary School , Malumichampatti, Coimbatore",
              date: "10.02.2020",
              organizing_unit: "KAHE – NSS",
              scheme_name: "Intramural Sports Competition",
              year_of_activity: "2019-2020",
            },
            {
              s_no: 37,
              activity_name: "Blood Donation Camp",
              date: "22.01.2020",
              organizing_unit: "YRC with Indian Medical Association Coimbatore",
              scheme_name: "Save Life",
              year_of_activity: "2019-2020",
            },
            {
              s_no: 38,
              activity_name: "Swachhata Pakhwada 15 Days Campaign 2019-2020",
              date: "16.01.2020",
              organizing_unit:
                "NSS with Field Outreach Bureau, Ministry of Information & Broadcasting, Government of India",
              scheme_name: "Swachhata Pakhwada",
              year_of_activity: "2019-2020",
            },
            {
              s_no: 39,
              activity_name: "Pesticide Free Agriculture",
              date: "08.01.2020",
              organizing_unit: "NSS with DHF Foundation",
              scheme_name: "Development of Agriculture",
              year_of_activity: "2019-2020",
            },
            {
              s_no: 40,
              activity_name: "Annual Special Camp",
              date: "04.01.2020 to 10.01.2020",
              organizing_unit: "NSS",
              scheme_name:
                '7 Days Annual Special Camp on "Youth for Rural Reconstruction"',
              year_of_activity: "2019-2020",
            },
            {
              s_no: 41,
              activity_name: "Indian Constitution Day",
              date: "02.12.2019",
              organizing_unit: "Coimbatore Humara Rights Forum",
              scheme_name: "Awareness Programme",
              year_of_activity: "2019-2020",
            },
            {
              s_no: 42,
              activity_name: "Tree Plantation Camp",
              date: "29.11.2019",
              organizing_unit:
                "KAHE NSS with Nandhu Coats, Rotary Club South Coimbatore",
              scheme_name: "Awareness Programme",
              year_of_activity: "2019-2020",
            },
            {
              s_no: 43,
              activity_name: "Swachh Bharat Mission & Poshan Abhiyan",
              date: "26.11.2019",
              organizing_unit:
                "KAHE NSS Government of India, Field Publicity Bureau, Ministry of Information and Broadcasting",
              scheme_name: "Awareness Programme",
              year_of_activity: "2019-2020",
            },
            {
              s_no: 44,
              activity_name: "Universal Childrens Day",
              date: "20.11.2019",
              organizing_unit:
                "KAHE NSS Government of India, Field Publicity Bureau, Ministry of Information and Broadcasting",
              scheme_name: "Awareness Programme",
              year_of_activity: "2019-2020",
            },
            {
              s_no: 45,
              activity_name: "Jal Shakthi Abhiyan",
              date: "23.10.2019",
              organizing_unit: "KAHE NSS, CIVIL DEPART",
              scheme_name: "Awareness Programme",
              year_of_activity: "2019-2020",
            },
            {
              s_no: 46,
              activity_name: "Swachhata Plastic Waste Free Village Campaign",
              date: "26.09.2019 to 27.09.2019",
              organizing_unit:
                "KAHE NSS, MALUMAGHAMPATTI, ARISIPALAYAM, NACHIPALAYAM, PALATHURAI PANCHAYETS",
              scheme_name: "Awareness Programme",
              year_of_activity: "2019-2020",
            },
            {
              s_no: 47,
              activity_name: "Annual Coimbatore Peace Festival",
              date: "29.08.2019",
              organizing_unit: "KAHE NSS",
              scheme_name: "Awareness Programme",
              year_of_activity: "2019-2020",
            },
            {
              s_no: 48,
              activity_name: "Awareness Programme Tuberculosis",
              date: "22.08.2019",
              organizing_unit:
                "KAHE NSS with Karpagam Faculty of Medical Science & Research and District TB Centre",
              scheme_name: "Revised National TB Control Programme (NNTCP)",
              year_of_activity: "2019-2020",
            },
            {
              s_no: 49,
              activity_name: "Breast Feeding Week 2019",
              date: "07.08.2019",
              organizing_unit:
                "KAHE NSS Government of India, Field Publicity Bureau, Ministry of Information and Broadcasting, Malumachampatti, Child Development Centre",
              scheme_name: "Awareness Programme",
              year_of_activity: "2019-2020",
            },
            {
              s_no: 50,
              activity_name: "Tree Plantation Camp",
              date: "28.07.2019",
              organizing_unit: "KAHE NSS with Nizhai Maiyam",
              scheme_name: "Awareness Programme",
              year_of_activity: "2019-2020",
            },
            {
              s_no: 51,
              activity_name:
                "Human Chain and Importance of Trees and Helmet Wearing",
              date: "20.07.2019",
              organizing_unit: "KAHE NSS with Nizhai Maiyam",
              scheme_name: "Public Awareness",
              year_of_activity: "2019-2020",
            },
            {
              s_no: 52,
              activity_name:
                "International Day Against Drug Abuse and Illicit Trafficking",
              date: "26.06.2019",
              organizing_unit:
                "KAHE NSS with Block Development Office, Malumachampatti Parchayet, Madukkarai Police Station",
              scheme_name: "Awareness Programme",
              year_of_activity: "2019-2020",
            },
            {
              s_no: 53,
              activity_name: "House Hold Survey Camp",
              date: "16.02.2019",
              organizing_unit: "College Hospital",
              scheme_name: "Survey",
              year_of_activity: "2018-2019",
            },
            {
              s_no: 54,
              activity_name: "House Hold Survey Camp",
              date: "5.02.2019 to 07.02.2019",
              organizing_unit:
                "KAHE NSS with Karapagam Medical College Hospital",
              scheme_name: "Internship",
              year_of_activity: "2018-2019",
            },
            {
              s_no: 55,
              activity_name: "House Hold Survey Camp",
              date: "29.01.2019 to 01.02.2019",
              organizing_unit:
                "KAHE NSS with Karapagam Medical College Hospital",
              scheme_name: "House Hold Survey Camp",
              year_of_activity: "2018-2019",
            },
            {
              s_no: 56,
              activity_name: "Blood Donation Camp",
              date: "25.01.2019",
              organizing_unit:
                "KAHE NSS with Karapagam Medical College Hospital",
              scheme_name: "Blood Donation",
              year_of_activity: "2018-2019",
            },
            {
              s_no: 57,
              activity_name: "Annual Special Camp",
              date: "21.12.2018 to 27.12.2018",
              organizing_unit: "NSS",
              scheme_name:
                '7 Days Annual Special Camp on "Youth for Rural Reconstruction"',
              year_of_activity: "2018-2019",
            },
            {
              s_no: 58,
              activity_name: "Child Abuse Programme at Schools",
              date: "12.12.2018",
              organizing_unit: "KAHE NSS with ARC Foundations",
              scheme_name: "Children Awareness",
              year_of_activity: "2018-2019",
            },
            {
              s_no: 59,
              activity_name: "Dengue Awareness Rally & Door to Door Canvass",
              date: "12.12.2018",
              organizing_unit:
                "KAHE NSS Government of India, Field Publicity Bureau, Ministry of Information and Broadcasting.",
              scheme_name: "Swachh Bharat",
              year_of_activity: "2018-2019",
            },
            {
              s_no: 60,
              activity_name: "Swatch Bharat Awareness Camp & Rally",
              date: "28.11.2018",
              organizing_unit:
                "KAHE NSS Government of India, Field Publicity Bureau, Ministry of Information and Broadcasting.",
              scheme_name: "Swachh Bharat",
              year_of_activity: "2018-2019",
            },
            {
              s_no: 61,
              activity_name: "Adhaar Enrollment/Updation Campaign",
              date: "26.11.2018",
              organizing_unit: "KAHE NSS",
              scheme_name: "Volunteer Service",
              year_of_activity: "2018-2019",
            },
            {
              s_no: 62,
              activity_name: "Indian Constitution Day",
              date: "26.11.2018",
              organizing_unit: "KAHE NSS",
              scheme_name: "Students Awareness",
              year_of_activity: "2018-2019",
            },
            {
              s_no: 63,
              activity_name: "Swatch Bharat Awareness Camp & Rally",
              date: "23.11.2018",
              organizing_unit:
                "KAHE NSS Government of India, Field Publicity Bureau, Ministry of Information and Broadcasting.",
              scheme_name: "Swachh Bharat",
              year_of_activity: "2018-2019",
            },
            {
              s_no: 64,
              activity_name: "Say No to Plastic Awareness among Shoppers",
              date: "23.11.2018",
              organizing_unit:
                "KAHE NSS Government of India, Field Publicity Bureau, Ministry of Information and Broadcasting.",
              scheme_name: "Swachh Bharat",
              year_of_activity: "2018-2019",
            },
            {
              s_no: 65,
              activity_name:
                "Dengue Awareness Rally & Door to Door Canvass at Malumichampatti",
              date: "22.11.2018",
              organizing_unit:
                "KAHE NSS Government of India, Field Publicity Bureau, Ministry of Information and Broadcasting.",
              scheme_name: "Swachh Bharat",
              year_of_activity: "2018-2019",
            },
            {
              s_no: 66,
              activity_name: "Keja Storm Relief Material",
              date: "20.11.2018",
              organizing_unit: "KAHE NSS",
              scheme_name: "Storm Relief",
              year_of_activity: "2018-2019",
            },
            {
              s_no: 67,
              activity_name: "Vigilance Day",
              date: "29.10.2018 to 03.11.2018",
              organizing_unit: "KAHE NSS",
              scheme_name: "Public Awareness",
              year_of_activity: "2018-2019",
            },
            {
              s_no: 68,
              activity_name: "Adhaar Enrollment/Inflation Campaign",
              date: "28.11.2018",
              organizing_unit: "KAHE NSS",
              scheme_name: "Special Activity",
              year_of_activity: "2018-2019",
            },
            {
              s_no: 69,
              activity_name: "Indian Constitution Day",
              date: "26.11.2018",
              organizing_unit: "KAHE NSS",
              scheme_name: "Awareness Programme",
              year_of_activity: "2018-2019",
            },
            {
              s_no: 70,
              activity_name: "Say No to Plastic Awareness among Shoppers",
              date: "23.11.2018",
              organizing_unit:
                "KAHE NSS Government of India, Field Publicity Bureau, Ministry of Information and Broadcasting.",
              scheme_name: "Swachh Bharat",
              year_of_activity: "2018-2019",
            },
            {
              s_no: 71,
              activity_name:
                "Dengue Awareness Rally & Door to Door Canvass at Malumichampatti",
              date: "22.11.2018",
              organizing_unit:
                "KAHE NSS Government of India, Field Publicity Bureau, Ministry of Information and Broadcasting.",
              scheme_name: "Swachh Bharat",
              year_of_activity: "2018-2019",
            },
            {
              s_no: 72,
              activity_name: "Vigilance Day",
              date: "29.10.2018 to 03.11.2018",
              organizing_unit: "KAHE NSS",
              scheme_name: "Awareness Programme",
              year_of_activity: "2018-2019",
            },
            {
              s_no: 73,
              activity_name: "International Day of Rural Women",
              date: "15.10.2018",
              organizing_unit: "KAHE NSS with ARC Foundations",
              scheme_name: "Womens Awareness",
              year_of_activity: "2018-2019",
            },
            {
              s_no: 74,
              activity_name: "World Students Day Malumichampatti",
              date: "15.10.2018",
              organizing_unit: "KAHE NSS with Nizhal Mayam",
              scheme_name: "Awareness Programme",
              year_of_activity: "2018-2019",
            },
            {
              s_no: 75,
              activity_name: "Organ Donation Day",
              date: "13.08.2018",
              organizing_unit:
                "KAHE NSS with Rajiv Gandhi Chronic Disease Health Care Awareness Association & Indira Gandhi Eye Bank of India Trust",
              scheme_name: "Public Awareness",
              year_of_activity: "2018-2019",
            },
            {
              s_no: 76,
              activity_name: "Unnat Bharat Abhiyan Summer Internship July 2018",
              date: "Jul-18",
              organizing_unit:
                "KAHE NSS Government of India, Field Publicity Bureau, Ministry of Information and Broadcasting.",
              scheme_name: "Unnat Bharat Abhiyan",
              year_of_activity: "2018-2019",
            },
            {
              s_no: 77,
              activity_name: "Human Chain and Importance of Helmet Wearing",
              date: "14.07.2018",
              organizing_unit: "KAHE NSS",
              scheme_name: "Awareness Programme",
              year_of_activity: "2018-2019",
            },
            {
              s_no: 78,
              activity_name: "International Yoga Day",
              date: "19.06.2018 to 21.06.2018",
              organizing_unit: "Government Middle School, Othakkalmandapam",
              scheme_name: "International Day",
              year_of_activity: "2018-2019",
            },
            {
              s_no: 79,
              activity_name: "Swachh Bharat – clean India",
              date: "23.02.2018",
              organizing_unit: "KAHE NSS",
              scheme_name: "Swachh Bharat",
              year_of_activity: "2017-2018",
            },
            {
              s_no: 80,
              activity_name: "Swachh Bharat Mission",
              date: "21.02.2018",
              organizing_unit: "KAHE NSS",
              scheme_name: "Awareness Programme",
              year_of_activity: "2017-2018",
            },
            {
              s_no: 81,
              activity_name: "Swachh Bharat – clean India",
              date: "20.02.2018",
              organizing_unit: "KAHE NSS",
              scheme_name: "Awareness Programme",
              year_of_activity: "2017-2018",
            },
            {
              s_no: 82,
              activity_name: "Swachh Bharat Mission",
              date: "19.02.2018",
              organizing_unit: "KAHE NSS",
              scheme_name: "Swachh Bharat",
              year_of_activity: "2017-2018",
            },
            {
              s_no: 83,
              activity_name: "World Leprosy Day",
              date: "30.01.2018",
              organizing_unit: "KAHE NSS",
              scheme_name: "World Leprosy Day",
              year_of_activity: "2017-2018",
            },
            {
              s_no: 84,
              activity_name: "Child Obesity Prevention in Schools",
              date: "09.01.2018",
              organizing_unit:
                "KAHE NSS with Karpagam Medical College Hospital",
              scheme_name: "Awareness Programme",
              year_of_activity: "2017-2018",
            },
            {
              s_no: 85,
              activity_name: "Dengue Awareness Programme",
              date: "04.01.2018",
              organizing_unit: "KAHE NSS",
              scheme_name: "Awareness Programme",
              year_of_activity: "2017-2018",
            },
            {
              s_no: 86,
              activity_name: "Blood Donation Camp",
              date: "20.12.2017",
              organizing_unit:
                "KAHE NSS with Karpagam Medical College Hospital",
              scheme_name: "Blood Donation",
              year_of_activity: "2017-2018",
            },
            {
              s_no: 87,
              activity_name: "Motivation Speech for NSS volunteers",
              date: "19.12.2017",
              organizing_unit: "KAHE NSS",
              scheme_name: "Students Awareness",
              year_of_activity: "2017-2018",
            },
            {
              s_no: 88,
              activity_name: "Swachh Survekshan Ranking",
              date: "14.12.2017 to 17.12.2017",
              organizing_unit: "KAHE NSS",
              scheme_name: "Awareness Programme",
              year_of_activity: "2017-2018",
            },
            {
              s_no: 89,
              activity_name: "Swachh Survekshan Ranking",
              date: "12.12.2017",
              organizing_unit: "KAHE NSS with ARC Foundations",
              scheme_name: "Swachh Bharat",
              year_of_activity: "2017-2018",
            },
            {
              s_no: 90,
              activity_name: "Annual Special Camp",
              date: "06.12.2017 to 12.12.2017",
              organizing_unit: "NSS",
              scheme_name:
                '7 Days Annual Special Camp on "Youth for Rural Reconstruction"',
              year_of_activity: "2017-2018",
            },
            {
              s_no: 91,
              activity_name: "AIDS Awareness Programme",
              date: "01.12.2017",
              organizing_unit:
                "KAHE NSS with Tamil Nadu AIDS Control Society Coimbatore.",
              scheme_name: "AIDS Awareness",
              year_of_activity: "2017-2018",
            },
            {
              s_no: 92,
              activity_name: "Breast Cancer Awareness",
              date: "25.10.2017",
              organizing_unit:
                "KAHE NSS with Karpagam Medical College Hospital",
              scheme_name: "Awareness Programme",
              year_of_activity: "2017-2018",
            },
            {
              s_no: 93,
              activity_name: "Kalam Libraries Cleaning Camp",
              date: "08.09.2017 to 09.09.2017",
              organizing_unit: "KAHE NSS with ARC Foundations",
              scheme_name: "Skill Development",
              year_of_activity: "2017-2018",
            },
            {
              s_no: 94,
              activity_name: "Swachhata pakhwada Campaign",
              date: "1.9.17 to 15.9.17",
              organizing_unit: "KAHE NSS",
              scheme_name: "Swachh Bharat",
              year_of_activity: "2017-2018",
            },
            {
              s_no: 95,
              activity_name: "Kalam Libraries Cleaning Camp",
              date: "12.09.2017 to 13.09.2017",
              organizing_unit: "KAHE NSS",
              scheme_name: "Community Service",
              year_of_activity: "2017-2018",
            },
            {
              s_no: 96,
              activity_name: "Blood Donation Camp",
              date: "05.09.2017",
              organizing_unit:
                "KAHE NSS with Karpagam Medical College Hospital",
              scheme_name: "Blood Donation",
              year_of_activity: "2017-2018",
            },
            {
              s_no: 97,
              activity_name: "Open Defecation awareness rally",
              date: "09.08.2017 to 15.08.2017",
              organizing_unit: "KAHE NSS with ARC Foundations",
              scheme_name: "Awareness Programme",
              year_of_activity: "2017-2018",
            },
            {
              s_no: 98,
              activity_name: "Dengue Awareness Programme",
              date: "09.08.2017 to 15.08.2017",
              organizing_unit: "KAHE NSS",
              scheme_name: "Swachh Bharat",
              year_of_activity: "2017-2018",
            },
            {
              s_no: 99,
              activity_name: "Breast Feeding Week",
              date: "07.08.2017",
              organizing_unit:
                "KAHE NSS with Karpagam Medical College Hospital",
              scheme_name: "Awareness Programme",
              year_of_activity: "2017-2018",
            },
            {
              s_no: 100,
              activity_name: "Koniamman Temple Volunteering Service",
              date: "04.08.2017",
              organizing_unit: "KAHE NSS with ARC Foundations",
              scheme_name: "Community Service",
              year_of_activity: "2017-2018",
            },
            {
              s_no: 101,
              activity_name: "World Leprosy Day",
              date: "30.01.2017",
              organizing_unit: "KAHE NSS",
              scheme_name: "World Leprosy Day",
              year_of_activity: "2016-2017",
            },
            {
              s_no: 102,
              activity_name: "Motivation Speech for NSS volunteers",
              date: "19.02.2017",
              organizing_unit: "KAHE NSS",
              scheme_name: "Awareness Programme",
              year_of_activity: "2016-2017",
            },
            {
              s_no: 103,
              activity_name: "World No Tobacco Day",
              date: "31.05.2017",
              organizing_unit:
                "KAHE NSS with Karpagam Medical College Hospital",
              scheme_name: "Public Awareness",
              year_of_activity: "2016-2017",
            },
            {
              s_no: 104,
              activity_name: "Medical Camp",
              date: "19.04.2017 to 29.04.2017",
              organizing_unit:
                "KAHE NSS with Karpagam Medical College Hospital",
              scheme_name: "Medical Camp",
              year_of_activity: "2016-2017",
            },
            {
              s_no: 105,
              activity_name: "Campus Cleaning",
              date: "10.03.2017",
              organizing_unit: "KAHE NSS",
              scheme_name: "Awareness Programme",
              year_of_activity: "2016-2017",
            },
            {
              s_no: 106,
              activity_name: "Blood Donation Camp",
              date: "05.03.2017",
              organizing_unit: "KAHE NSS with Canara Bank",
              scheme_name: "Awareness Programme",
              year_of_activity: "2016-2017",
            },
            {
              s_no: 107,
              activity_name: "Workshop on Implications of GST",
              date: "16.02.2017",
              organizing_unit: "KAHE",
              scheme_name: "Workshop on implications of GST",
              year_of_activity: "2016-2017",
            },
            {
              s_no: 108,
              activity_name:
                "Awareness programme on Implementation of Cashless transactions",
              date: "12.02.2017",
              organizing_unit: "KAHE",
              scheme_name:
                "Awareness programme on implementation of Cashless transactions",
              year_of_activity: "2016-2017",
            },
            {
              s_no: 109,
              activity_name: "Vehicle Emission Programme",
              date: "12.02.2017",
              organizing_unit: "KAHE NSS",
              scheme_name: "Public Awareness",
              year_of_activity: "2016-2017",
            },
            {
              s_no: 110,
              activity_name:
                "Implementation of Demonstration Cash Less Transaction",
              date: "12.02.2017",
              organizing_unit:
                "KAHE NSS with Karpagam Medical College Hospital",
              scheme_name: "Awareness Programme",
              year_of_activity: "2016-2017",
            },
            {
              s_no: 111,
              activity_name: "National Youth Day",
              date: "12.01.2017",
              organizing_unit: "KAHE NSS",
              scheme_name: "Awareness",
              year_of_activity: "2016-2017",
            },
            {
              s_no: 112,
              activity_name: "Digital India (VITTIVA SAKSHARATA ABBYAN)",
              date: "11.01.2017",
              organizing_unit: "KAHE NSS",
              scheme_name: "Digital India",
              year_of_activity: "2016-2017",
            },
            {
              s_no: 113,
              activity_name: "Campus Cleaning",
              date: "06.01.2017",
              organizing_unit: "KAHE NSS",
              scheme_name: "Swachh Bharat",
              year_of_activity: "2016-2017",
            },
            {
              s_no: 114,
              activity_name: "Annual Special Camp",
              date: "19.12.2016",
              organizing_unit: "NSS",
              scheme_name:
                'Annual Special Camp on "Youth for Rural Reconstruction"',
              year_of_activity: "2016-2017",
            },
            {
              s_no: 115,
              activity_name: "AIDS Awareness Programme",
              date: "01.12.2016",
              organizing_unit:
                "KAHE NSS with Tamil Nadu AIDS Control Society Coimbatore.",
              scheme_name: "AIDS Awareness",
              year_of_activity: "2016-2017",
            },
            {
              s_no: 116,
              activity_name: "Vigilance Week",
              date: "05.11.2016",
              organizing_unit: "KAHE NSS with Indian Bank",
              scheme_name: "Vigilance Week",
              year_of_activity: "2016-2017",
            },
            {
              s_no: 117,
              activity_name: "Breast Cancer Awareness Programme Rally",
              date: "04.11.2016",
              organizing_unit: "KAHE NSS",
              scheme_name: "Awareness Programme",
              year_of_activity: "2016-2017",
            },
            {
              s_no: 118,
              activity_name: "Breast Cancer Awareness",
              date: "26.10.2016",
              organizing_unit:
                "KAHE NSS with Karpagam Medical College Hospital",
              scheme_name: "Breast Cancer Week",
              year_of_activity: "2016-2017",
            },
            {
              s_no: 119,
              activity_name: "Village Cleaning Camp",
              date: "02.10.2016",
              organizing_unit:
                "KAHE NSS with Maddukrati Block Development Office, Government of India, Field Publicity Bureau, Ministry of Information and Broadcasting",
              scheme_name: "Swachh Bharat",
              year_of_activity: "2016-2017",
            },
            {
              s_no: 120,
              activity_name: "Campus Cleaning",
              date: "02.10.2016",
              organizing_unit: "KAHE NSS",
              scheme_name: "Swachh Bharat",
              year_of_activity: "2016-2017",
            },
            {
              s_no: 121,
              activity_name: "Organ Donation Day",
              date: "22.08.2016",
              organizing_unit: "KAHE NSS",
              scheme_name: "Public Awareness",
              year_of_activity: "2016-2017",
            },
            {
              s_no: 122,
              activity_name: "Tree Plantation",
              date: "15.08.2016",
              organizing_unit: "KAHE NSS",
              scheme_name: "Awareness Programme",
              year_of_activity: "2016-2017",
            },
            {
              s_no: 123,
              activity_name: "Blood Donation Camp",
              date: "15.08.2016",
              organizing_unit: "KAHE NSS with Canara Bank",
              scheme_name: "Blood Donation",
              year_of_activity: "2016-2017",
            },
            {
              s_no: 124,
              activity_name: "Breast Feeding Week",
              date: "07.08.2016",
              organizing_unit:
                "KAHE NSS with Karpagam Medical College Hospital",
              scheme_name: "Breast feeding Week",
              year_of_activity: "2016-2017",
            },
            {
              s_no: 125,
              activity_name: "Swachhata Bharath Pakhwada",
              date: "26.01.2016 to 28.01.2016",
              organizing_unit:
                "KAHE NSS with Maddukrati Block Development Office, Government of India, Field Publicity Bureau, Ministry of Information and Broadcasting and Rotaract Galaxy Coimbatore.",
              scheme_name: "Swachh Bharat",
              year_of_activity: "2016-2017",
            },
            {
              s_no: 126,
              activity_name: "Tree Plantation",
              date: "15.03.2016",
              organizing_unit: "KAHE NSS",
              scheme_name: "Tree Plantation",
              year_of_activity: "2015-2016",
            },
            {
              s_no: 127,
              activity_name: "Annual Special Camp",
              date: "03.01.2016 to 09.01.2016",
              organizing_unit: "NSS",
              scheme_name:
                '7 Days Annual Special Camp on "Youth for Rural Reconstruction"',
              year_of_activity: "2015-2016",
            },
            {
              s_no: 128,
              activity_name: "Awareness programme on Environmental Issues",
              date: "07.01.2016",
              organizing_unit:
                "Karpagam Academy of Higher Education & Myleripalayam Panchayat",
              scheme_name: "Awareness Programme",
              year_of_activity: "2015-2016",
            },
            {
              s_no: 129,
              activity_name: "Blood Donation Camp",
              date: "05.11.2015",
              organizing_unit: "KAHE NSS",
              scheme_name: "Public Awareness",
              year_of_activity: "2015-2016",
            },
            {
              s_no: 130,
              activity_name: "Awareness programme on Health & Hygiene",
              date: "26.10.2015",
              organizing_unit:
                "Karpagam Academy of Higher Education & Seerapalayam Panchayat",
              scheme_name: "Awareness Programme",
              year_of_activity: "2015-2016",
            },
            {
              s_no: 131,
              activity_name: "Medical Camp",
              date: "02.10.2015",
              organizing_unit: "KAHE NSS",
              scheme_name: "Health & Hygiene",
              year_of_activity: "2015-2016",
            },
            {
              s_no: 132,
              activity_name: "Sanitation Awareness Campaign Village cleaning",
              date: "02.10.2015",
              organizing_unit: "KAHE NSS",
              scheme_name: "Awareness Programme",
              year_of_activity: "2015-2016",
            },
            {
              s_no: 133,
              activity_name: "Blood Donation Camp",
              date: "17.09.2015",
              organizing_unit: "KAHE NSS",
              scheme_name: "Community Service",
              year_of_activity: "2015-2016",
            },
            {
              s_no: 134,
              activity_name: "Legal Literacy Camp",
              date: "10.09.2015",
              organizing_unit: "KAHE - NSS",
              scheme_name: "Extension Activity",
              year_of_activity: "2015-2016",
            },
            {
              s_no: 135,
              activity_name: "Environment Awareness Camp",
              date: "07.09.2015",
              organizing_unit: "KAHE NSS",
              scheme_name: "Public Awareness",
              year_of_activity: "2015-2016",
            },
            {
              s_no: 136,
              activity_name: "Tree Plantation",
              date: "15.08.2015",
              organizing_unit: "KAHE NSS",
              scheme_name: "Awareness Programme",
              year_of_activity: "2015-2016",
            },
            {
              s_no: 137,
              activity_name: "Tree Plantation",
              date: "15.08.2015",
              organizing_unit: "KAHE NSS",
              scheme_name: "Awareness Programme",
              year_of_activity: "2015-2016",
            },
          ],
        },
      },
    ],
  },
  {
    id: 4,
    tab_title: "Gallery",
    section: [
      {
        id: 1,
        title: "Covid-19 Awareness",
        images: ["/kahe-logo.png", "/kahe-logo.png", "/kahe-logo.png"],
      },
      {
        id: 2,
        title: "Ek Bharat Shreshtha Bharat",
        images: ["/kahe-logo.png", "/kahe-logo.png", "/kahe-logo.png"],
      },
      {
        id: 2,
        title: "Grama Sabha Meeting",
        images: ["/kahe-logo.png", "/kahe-logo.png", "/kahe-logo.png"],
      },
      {
        id: 2,
        title: "ANNUAL SPECIAL CAMP",
        images: ["/kahe-logo.png", "/kahe-logo.png", "/kahe-logo.png"],
      },
      {
        id: 2,
        title: "Agrothon 2020- KIDS Marathon",
        images: ["/kahe-logo.png", "/kahe-logo.png", "/kahe-logo.png"],
      },
      {
        id: 2,
        title: "Swachh Bharat Mission & Poshan Abhiyaan",
        images: ["/kahe-logo.png", "/kahe-logo.png", "/kahe-logo.png"],
      },
      {
        id: 2,
        title: "International Yoga Day",
        images: ["/kahe-logo.png", "/kahe-logo.png", "/kahe-logo.png"],
      },
      {
        id: 2,
        title: "Campus Cleaning",
        images: ["/kahe-logo.png", "/kahe-logo.png", "/kahe-logo.png"],
      },
      {
        id: 2,
        title: "Childrens Day",
        images: ["/kahe-logo.png", "/kahe-logo.png", "/kahe-logo.png"],
      },
      {
        id: 2,
        title: "Importance of National Flag and Helmet Awareness",
        images: ["/kahe-logo.png", "/kahe-logo.png", "/kahe-logo.png"],
      },
      {
        id: 2,
        title: "Medical Camp",
        images: ["/kahe-logo.png", "/kahe-logo.png", "/kahe-logo.png"],
      },
      {
        id: 2,
        title: "Womens Day",
        images: ["/kahe-logo.png", "/kahe-logo.png", "/kahe-logo.png"],
      },
      {
        id: 2,
        title: "Blood Donation",
        images: ["/kahe-logo.png", "/kahe-logo.png", "/kahe-logo.png"],
      },
      {
        id: 2,
        title: "Breastfeeding Week",
        images: ["/kahe-logo.png", "/kahe-logo.png", "/kahe-logo.png"],
      },
      {
        id: 2,
        title: "Tree Plantation",
        images: ["/kahe-logo.png", "/kahe-logo.png", "/kahe-logo.png"],
      },
    ],
  },
];
